openapi: 3.0.0
info:
  description: golang-service-template
  title: "golang-service-template"
  version: "1.0.0"

paths:
  /sample:
    get:
      tags:
        - Sample
      summary: Sample endpoint definition
      operationId: SampleHandler
      responses:
        '200':
          description: Dummy sample response

components:
  schemas:

    ApiMessage:
      type: object
      properties:
        code:
          description: "Status code"
          type: "integer"
        subCode:
          description: "Api specific status code"
          type: "integer"
        data:
          example: "{}"
          description: "Backend content"
          type: "object"
